version: "3.1"
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: ebooks
      POSTGRES_USER: ebooks
      POSTGRES_DB: ebooks
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
    restart: always

volumes:
  postgres:
