#! /usr/bin/env bash

# get script directory
SCRIPT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
# echo "SCRIPT_DIR: $SCRIPT_DIR"
docker run --rm -u $(id -u):$(id -g) -v $SCRIPT_DIR/../test-data:/ebooks calibre ebook-meta "$@"